### ISSUE TITLE
目前似乎在 PDF 文件内定位不准？

### ISSUE THREAD

**Issue by mtf-tpxs** [clerkma/ptex-ng#10]
请教~~
我使用的是 W32TeX 上 2016.6.3（4） 更新的 pTeX-ng，放到了 windows 下的 TeX Live 2016 里，然后发现：
1.交叉引用的超链接定位不准；
2.PDF 书签定位不准。
使用 ptex-ng 编译时出现此问题，但换用 uptex + dvipdfmx 则无此问题。

最小示例（共有两个）：
（因为代码发上来时总出问题，放到这里：见下边回复。）
请问是哪里出了问题？谢谢！

**Comment by clerkma** [comment]
提供PDF阅读器信息和无警告的示例给我（第一个警告尤其多，裸写的内容缺参数）。这里面（dpx和dvipdfmx）的坐标算法是有一定差别的，我在Adobe的阅读器上并没有能够重现类似问题（LaTeX+Hyperref）。

**Comment by mtf-tpxs** [comment]
是这样的，刚才发代码上来时，尖括号里的东西都丢了，我本来是写了的……（我还不太会用GitHub……）

所以刚才把代码编辑掉了，刚刚发到了豆瓣日记上，您看看：
https://www.douban.com/note/563436257/

**Comment by mtf-tpxs** [comment]
PDF 阅读器就是最新的 Adobe Acrobat Reader DC。

**Comment by clerkma** [comment]
可能还是会有问题，但是测试的例子是通过了。明天你测测看。

**Comment by mtf-tpxs** [comment]
非常感谢！刚刚重新测试那两个例子，没问题~~

**Comment by mtf-tpxs** [comment]
刚刚发现，横排时正常，但竖排时还是有问题。我使用的版本是W32TeX上2016.8.4更新的版本。
例子还是在下边这个链接里，是最上边用横线隔出来的那几行：
https://www.douban.com/note/563436257/
谢谢！
