### ISSUE TITLE
在目前版本（2016.6.23）中使用 graphicx 宏包出现问题

### ISSUE THREAD

**Issue by mtf-tpxs** [clerkma/ptex-ng#12]
上次更新时（W32TeX，2016.6.21，在 TeX Live 2016 中使用）尚无此问题；
目前在 TL 2016 中的 (e)upTeX + dvipdfmx 也没问题；
昨天更新之后（W32TeX，2016.6.23），重新编译一个之前的文档，发现使用 graphicx 宏包时出现问题。
例子如下：

\input eplain
\beginpackages
\usepackage[dvipdfmx]{graphicx}
\endpackages

\tate
\vsize=300pt
\overfullrule=0cm

\special{pdf:mapline uprml-v UniGB-UTF16-V :0:simsun.ttc}
\font\songti=upjisr-v at 24pt
\global\songti

\def\test#1{\nobreak\raise1.2zw\hbox to 0zh{\hskip-1zh\relax\rotatebox[origin=lb]{60}{{#1}}\hss}}

中\test{中文測試}%
文\test{中文測試}%
測\test{中文測試}%
試\test{中文測試}%

\bye

乍一看似乎是丢失了内容，但若把其中的

中\test{中文測試}%
文\test{中文測試}%
測\test{中文測試}%
試\test{中文測試}%

多重复几次（六、七次的样子吧），可以看到，是位置不对了。

请您看看是否需要解决一下？谢谢！

**Comment by clerkma** [comment]
刚提交的例子测试通过了。

**Comment by mtf-tpxs** [comment]
现在没问题了，非常感谢！
