### ISSUE TITLE
设置页面尺寸的\special命令无效？

### ISSUE THREAD

**Issue by Man-Ting-Fang** [clerkma/ptex-ng#17]
再次请教~~
W32TeX上面2016.8.4版本（其实以前也是），dvipdfm(x)的页面尺寸命令无效，即类似于下边这样的命令无效：
\special{pdf:pagesize width 8in height 12in}
（取自dvipdfmx文档。）
请问是只能用\pdfpagewidth、\pdfpageheight吗？

另外，之前提到过的PDF文件定位，还是有一些问题，我回复在原来那里了，不知已关闭的是否还有提示。这里是链接：
https://github.com/clerkma/ptex-ng/issues/10
谢谢！

**Comment by clerkma** [comment]
我这周暂时没时间修，你稍等几天。

**Comment by mtf-tpxs** [comment]
OK~~

**Comment by clerkma** [comment]
开始拔草了～

**Comment by clerkma** [comment]
我仔细看了一下dvipdfmx的代码。实际上，pagesize等相关的special是在处理每一页的时候先读取的，而后就是处理页面上的元素，相关的special也会读一遍，但是不一定会执行。
我的代码里面，是没有先找到本页面上的special命令，所以控制页面尺寸的special就不会起作用。
以后还是使用pdfpagewidth/height来控制页面的大小吧。
