### ISSUE TITLE
仍然有些尚未支持？

### ISSUE THREAD

**Issue by Man-Ting-Fang** [clerkma/ptex-ng#20]
下载安装了W32TeX上最新的版本后，发现：

一、仍不支持`\ifmbox`；
二、`\textbaselineshiftfactor`、`\scriptbaselineshiftfactor`、`\scriptscriptbaselineshiftfactor`默认均为`0`，但是upTeX等默认分别为`1000`、`700`、`500`；
三、dvipdfmx的部分（原有）`\special`仍不支持（不限于https://github.com/clerkma/ptex-ng/issues/17 ）。另外，今天看W32TeX上dvipdfmx新增的说明dvipdfmx.pdf，貌似加了些新东西，比如字体映射中的`-l`选项（？）。

另外有两个问题请教：

一、`\textbaselineshiftfactor`、`\scriptbaselineshiftfactor`、`\scriptscriptbaselineshiftfactor`这三个命令应该如何使用？能否给个能够显示出它们的效果的示例？（我怎么试也不成功，大概是理解错了。）
二、dvipdfmx的字体映射，用`unicode`作为关键字时，后边加`-w 1`选项可以变为竖排，但貌似只有汉字之类转过来了，标点还是不对，请问这是什么原因，应该怎样解决？
测试例子：
```TeX
\tate
\vsize=100mm
\special{pdf:mapline uprml-v unicode ipaexm.ttf -w 1}
%下边这行却可以，为什么？
%\special{pdf:mapline urml-v unicode ipaexm.ttf -w 1}
\font\ipaexmv=upjisr-v
\ipaexmv
漢字。
\bye
```
谢谢！

**Comment by aminophen** [comment]
Hi,

I'm a member of Japanese TeX Development Community (current maintainer of pTeX and related software/macros), and I can explain some in English.

>  一、\textbaselineshiftfactor、\scriptbaselineshiftfactor、\scriptscriptbaselineshiftfactor这三个命令应该如何使用？能否给个能够显示出它们的效果的示例？（我怎么试也不成功，大概是理解错了。）

pTeX and upTeX in TeX Live 2015 had a following problem: "Japanese characters inside explicit boxes in math mode" are shifted by \ybaselineshift, and "Alphabets inside explicit boxes in math mode" are shifted by 2\ybaselinshift.

~~~~ tex
\ybaselineshift=1zw
漢字pqr$abc\hbox{xyzあいう}$かきく
~~~~

![img_1445](https://cloud.githubusercontent.com/assets/9957466/25804415/b0e7f55a-3436-11e7-9642-55bf8a2c61e5.JPG)

in TeX Live 2016, we made a change in the shift amount of explicit boxes inside math mode. That is, we introduced three primitives (\{text,script,scriptscript}baselineshiftfactor) to specify the ratio of reverse shift. The default ratio are 1000, 700, 500 respectively for 2016.

![img_1446](https://cloud.githubusercontent.com/assets/9957466/25804442/c616cb18-3436-11e7-8ba2-4c69f39bc316.JPG)

When we set all these parameters to zero, the old behavior in 2015 is recovered.

**Comment by aminophen** [comment]
the above screenshots are taken from [this slide](https://osdn.net/projects/eptex/docs/tc16ptex/ja/1/tc16ptex.pdf%20) by Kitagawa-san, which is written in Japanese but may help you.

**Comment by aminophen** [comment]
But I don't know whether pTeX-ng supports `\{text,script,scriptscript}baselineshiftfactor` (added in pTeX for TeX Live 2016) and `\ifmbox` (added in pTeX for TeX Live 2017)

**Comment by Man3Ting2Fang1** [comment]
>  The above screenshots are taken from this slide by Kitagawa-san, which is written in Japanese but may help you.

Thank you very much! My understand was wrong, but I think I get it now (hope so).

**Comment by Man3Ting2Fang1** [comment]
> 二、dvipdfmx的字体映射，用unicode作为关键字时，后边加-w 1选项可以变为竖排，但貌似只有汉字之类转过来了，标点还是不对，请问这是什么原因，应该怎样解决？

之前的问题二，原来更新一下dvipdfmx就好了，不过还没试过ApTeX。

**Comment by Man-Ting-Fang** [comment]
今天更新了W32TeX上2017-09-10版本，发现仍然有些问题：

一、三个`baselineshiftfactor`默认值仍均为`0`，请问这是有意如此设置的吗？

二、字体映射使用`unicode`作为cmap时，`-w 1`产生的竖排标点还是不对。

三、不支持字体映射选项`-l`。

不过奇怪的是，在1楼的例子中，如果写
```TeX
\special{pdf:mapline uprml-v unicode ipaexm.ttf -w 1}
```
竖排标点不对；但如果写
```TeX
\special{pdf:mapline uprml-v unicode ipaexm.ttf -w 1 -l fwid}
```
那个句号又对了，当然，`-l`选项还是不行，而且我也没对更多的标点进行过测试。
（我不知道TrueType字体是否支持fwid？上边例子里只是随手一写，其实我是想在思源的日韩字体上用，思源字体是支持的，新版的DVIPDFMx用`-l fwid`可以达到我想要的效果。）

**Comment by clerkma** [comment]
1. 应该是我把赋值的位置写错了
2. 3. 可能是版本有差异。fwid这个feature不是所有的字体都有，尤其是大陆的字体。

**Comment by Man-Ting-Fang** [comment]
感谢您的回复。
今天又发现，新版的dvipdfmx，对Fandol字体也可以用`unicode`作cmap了，暂时没发现什么问题；ApTeX目前还要用`UniGB-UTF16-H/V`这样的cmap才行，用`unicode`则会乱码，并产生一大堆警告，跟这里类似：
http://bbs.ctex.org/forum.php?mod=redirect&goto=findpost&ptid=76617&pid=451245
这个应该也是dpx的版本问题吧。

**Comment by Man-Ting-Fang** [comment]
今天试了下W32TeX上2017-10-09版本，发现这个issue里提到的问题应该是都修复好了？我先关掉这个issue了～～感谢@clerkma ！
