### ISSUE TITLE
\shellescape 未定义

### ISSUE THREAD

**Issue by Stone-Zeng** [clerkma/ptex-ng#22]
`\shellescape` 未定义，导致 LaTeX3 目前无法使用。

```tex
\documentclass{article}
\usepackage{expl3}

\begin{document}
Hello, world!
\end{document}
```

LaTeX3 在 2017-05-27 新加的 `\c_sys_shell_escape_int` 定义需要 `\pdftex_shellescape:D`，没有 `\shellescape` 的话会报错。

测试环境：LaTeX3 release 2017/07/19，TeX Live 2017，aptex 2016/08/08。

**Comment by prinwis** [comment]
用最新源码编译出来的也一样出错，不过最近一次更新是5月9号......

**Comment by Stone-Zeng** [comment]
之前 `ctex` 宏包是能用的吧，几个月之前我还试过的。

**Comment by clerkma** [comment]
@Stone-Zeng 更新了，在`9e77b139bedaeae8828961bd9e43cdc0661fe2a3`中加了shellescape，签出代码重新编译然后运行`fmtutil -sys --byengine=ptex-ng`更新一下fmt文件即可。如需Windows版本，请注明。

**Comment by Stone-Zeng** [comment]
最好还是给一下 windows 版本的可执行文件吧。

**Comment by clerkma** [comment]
[build-20170905.zip](https://github.com/clerkma/ptex-ng/files/1277492/build-20170905.zip)

**Comment by Stone-Zeng** [comment]
运行 `fmtutil` 的时候提示 `did not find entry for byengine=ptex-ng, skipped` 怎么办？

**Comment by clerkma** [comment]
没安装？

**Comment by Stone-Zeng** [comment]
是不是要在 `texmf-local` 里面加一个 `fmtutil.cnf？但这个东西不太会写。。

**Comment by clerkma** [comment]
我明天发个专栏写怎么装吧

**Comment by Stone-Zeng** [comment]
感谢大佬 👍 

https://zhuanlan.zhihu.com/p/29370328
