### ISSUE TITLE
如何正确插入图片？

### ISSUE THREAD

**Issue by xiaoyaoE** [clerkma/ptex-ng#26]
使用\includegraphics插入pdf文件需要指定bb参数，很麻烦，使用eps格式显示空白，请问ptex-ng如何插入图片？

**Comment by clerkma** [comment]
最新的版本开始支持`-shell-escape`选项，如下面的代码（a.tex）：
```
\documentclass{article}
\usepackage[dvipdfmx]{graphicx}
\begin{document}
\includegraphics[width=20pt]{test.png}
\end{document}
```
可以使用命令`platex-ng -shell-escape a.tex`编译。
现有的引擎对eps都没有原生支持，需要使用`epstopdf`自行转换为PDF文件后再插图。
