### ISSUE TITLE
提供 linux 和 mac 版本的下载

### ISSUE THREAD

**Issue by stone-zeng** [clerkma/ptex-ng#27]
目前新版本的 aptex 只有在 W32TeX 上可以下载到，tltexjp 上面的又太老。请问有办法直接下载 linux 和 mac 版本的吗？用 travis 的话每次要重新编译，太麻烦了。

**Comment by aminophen** [comment]
I’m a member of texjporg

> 目前新版本的 aptex 只有在 W32TeX 上可以下载到，tltexjp 上面的又太老。

Sorry for that, but we don’t have enough time to rebuild binaries for multiple platforms frequently, and we don’t have enough time to discuss when to update binaries in tltexjp.

**Comment by clerkma** [comment]
@Stone-Zeng 我可以把我的TeX挂到CTAN上面去更新。这样可以？

**Comment by Stone-Zeng** [comment]
可以可以。

**Comment by nanmu42** [comment]
可以在各个CI编译成功后推送文件到Dropbox或者各种云。
这样就有最新的开发版了。

**Comment by Xtricman** [comment]
那MikTex用户怎么办，没有人权吗？要自己编译安装？

**Comment by clerkma** [comment]
@Xtricman MikTeX的运行时和TeX Live的不一样。所以按照`build-msvc`里面的编译脚本编译出来的东西也不能直接在MikTeX直接用。暂时没时间弄兼容MikTeX的版本。

**Comment by nanmu42** [comment]
李阿姨发个Docker版本？（滑稽）

**Comment by clerkma** [comment]
@nanmu42 好主意啊（计画通り

**Comment by clerkma** [comment]
我把编译好的文件，都放到阿里云里面去了。即

* [aptex-linux-x86_64.zip](http://aptex.oss-cn-beijing.aliyuncs.com/aptex-linux-x86_64.zip) (gcc-8.3.0, Ubuntu 19.04)
* [aptex-macos-x86_64.zip](http://aptex.oss-cn-beijing.aliyuncs.com/aptex-macos-x86_64.zip) (clang-1001.0.46.4, macOS Mojave)
* [aptex-msvc-x86.zip](http://aptex.oss-cn-beijing.aliyuncs.com/aptex-msvc-x86.zip) (Visual Studio 2019)
* [aptex-msvc-x86_64.zip](http://aptex.oss-cn-beijing.aliyuncs.com/aptex-msvc-x86_64.zip) (Visual Studio 2019)

至于做成Docker，我前一阵试了一下完整的TeX Live 2019，需要6GB以上空间（虽然删了文档后会变小一些）。所以直接跟TeX Live放在一起还是会比较大。所以，还是可能要删减内容。这个我之后再想想吧，如果有了docker镜像的话，我直接更新到README里面。
