### ISSUE TITLE
\pdfpagewidth/height when magnification is used

### ISSUE THREAD

**Issue by zr-tex8r** [clerkma/ptex-ng#29]
Suppose you have the following source:

```tex
\mag=2000
\pdfpagewidth=100mm \pdfpageheight=100mm
Hello! \bye
```

When compiling with pdftex, you’ll get a PDF document with size 200mm×200mm, because `\pdfpagewidth/height` respect magnification and thus `100mm` equals actually to 200mm.

When compiling with ptex-ng, however, you’ll get a PDF document with size 100mm×100mm. It seems ptex-ng’s `\pdfpagewidth/height` does not respect maginification.

Is this an intended behaviour?

**Comment by clerkma** [comment]
Fixed in commit [d2badf78fa5f098def73194aa6730e2c9f59b095](https://github.com/clerkma/ptex-ng/commit/d2badf78fa5f098def73194aa6730e2c9f59b095).
