### ISSUE TITLE
ptex-ng不支持ctex的CJKfntef包，那么请问有中文字体配置的示例么？

### ISSUE THREAD

**Issue by Jhering** [clerkma/ptex-ng#34]
如何使用win系统中的字体？
通过什么方式设置？有文档么？
怎么搜索也搜索不到啊。

**Comment by clerkma** [comment]
ctex官方不支持在ApTeX/ptex-ng里面使用`CJKfntef`。
看文档的话，可以使用`texdoc ctex`看。
