### ISSUE TITLE
生成fmt出错

### ISSUE THREAD

**Issue by minnyres** [clerkma/ptex-ng#36]
系统环境为OpenSuse， 安装的是官方源中提供的TexLive，版本信息为
(TeX Live 2018/TeX Live for SUSE Linux) 

安装方式为执行`./build-pTeX-ng.sh`编译，然后把生成的可执行文件复制到/usr/bin目录下

执行`sudo fmtutil -sys --byengine ptex-ng`，输出信息为

fmtutil: fmtutil is using the following fmtutil.cnf files (in precedence order):
fmtutil:   /etc/texmf/web2c/fmtutil.cnf
fmtutil:   /usr/share/texmf/web2c/fmtutil.cnf
fmtutil: fmtutil is using the following fmtutil.cnf file for writing changes:
fmtutil:   /etc/texmf/web2c/fmtutil.cnf
fmtutil [INFO]: writing formats under /var/lib/texmf/web2c
fmtutil [INFO]: --- remaking aplatex with ptex-ng
fmtutil [INFO]: --- remaking aptex with ptex-ng
fmtutil [INFO]: did not find entry for byengine=ptex-ng, skipped
fmtutil [INFO]: Not selected formats: 51
fmtutil [INFO]: Not available formats: 2
fmtutil [INFO]: Total formats: 53
fmtutil [INFO]: exiting with status 0

**Comment by clerkma** [comment]
`fmtutil [INFO]: did not find entry for byengine=ptex-ng, skipped`
