### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by tan9p** [clerkma/ptex-ng#39]
debian 9 + gcc 6.3.0
源代码编译安装，完成后将aptex,ptex-ng,lsotfea拷贝到/usr/bin/中，并建立软链接 aplatex和platex-ng.
然后拷贝了相应的文件，运行 sudo fmtutil -sys --byengine ptex-ng  .

使用中 aplatex test.tex提示Invalid argument错误

This is Asiatic pTeX, Version 3.14159265 (preloaded format=aplatex)
entering extended mode
(test.tex
pLaTeX2e <2016/11/29u01> (based on LaTeX2e <2017/01/01> patch level 3)
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
(article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(size10.clo)) (test.aux) [1aplatex: �   �: Invalid argument

test.log 文件卡在了[1这块：

This is Asiatic pTeX, Version 3.14159265 (preloaded format=aplatex 2019.7.10)  10 JUL 2019 23:16
 entering extended mode
 **test.tex
 (test.tex
 pLaTeX2e <2016/11/29u01> (based on LaTeX2e <2017/01/01> patch level 3)
 Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
 (article.cls
 Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
 (size10.clo
 File: size10.clo 2014/09/29 v1.4h Standard LaTeX file (size option)
 LaTeX Font Info:    Font shape `JT2/mc/m/n' will be
 (Font)              scaled to size 9.6222pt on input line 54.
 LaTeX Font Info:    Font shape `JY2/mc/m/n' will be
  (Font)              scaled to size 9.6222pt on input line 54.
  )
 \c@part=\count82
 \c@section=\count83
 \c@subsection=\count84
 \c@subsubsection=\count85
 \c@paragraph=\count86
 \c@subparagraph=\count87
 \c@figure=\count88
 \c@table=\count89
 \abovecaptionskip=\skip41
\lowcaptionskip=\skip42
 \bibindent=\dimen118
 ) (test.aux)
 LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 3.
 LaTeX Font Info:    ... okay on input line 3.
 LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 3.
 LaTeX Font Info:    ... okay on input line 3.
 LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 3.
 LaTeX Font Info:    ... okay on input line 3.
 LaTeX Font Info:    Checking defaults for IL2/cmr/m/n on input line 3.
 LaTeX Font Info:    ... okay on input line 3.
 LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 3.
 LaTeX Font Info:    ... okay on input line 3.
 LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 3.
 LaTeX Font Info:    ... okay on input line 3.
 LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 3.
 LaTeX Font Info:    ... okay on input line 3.
 LaTeX Font Info:    Checking defaults for JY2/mc/m/n on input line 3.
 LaTeX Font Info:    ... okay on input line 3.
 LaTeX Font Info:    Checking defaults for JT2/mc/m/n on input line 3.
 LaTeX Font Info:    ... okay on input line 3.
 [1

test.tex 文件如下
\documentclass{article}
\begin{document}
她说道：“你这贱人”。随后便抬起了手。
\end{document}

**Comment by clerkma** [comment]
你可以试试docker镜像里面的platex-ng。
拉取最新镜像：`docker pull clerkma/texlive2019:20190711`。
我的测试环境，无论是debian还是ubuntu，都不安装源内的texlive。
问题未能复现。等你反馈。

**Comment by tan9p** [comment]
我的debian是32位的(i686)没法装docker啊。（在网上也没有搜到怎么在32位的系统上面装docker）
上面的问题会不会和系统是32位有关？
我搜了下 Invalid Argument，发现代码里有太多的Invalid Argument,不好调试呀：）

**Comment by clerkma** [comment]
在debian 10上能复现，预计明天能解决。

**Comment by clerkma** [comment]
已经修好了，你拉取最新代码重新编译一下试试看。

**Comment by tan9p** [comment]
debian 9 i686 仍然不行，仍然提示 Invalid Argument.
log文件停住的位置仍然是[1

**Comment by clerkma** [comment]
我装了debian-9.9.0-i386，编译之后依然不能复现。
你可以这样，拖最新的代码编译ptex-ng。
然后再拖`git clone --depth=1 https://github.com/clerkma/ptex-ng-dist.git`。
拖完之后，建立一个文件夹`ptex-ng-dist/bin/linux-i386`，把编译好的`aptex`复制到这个文件夹。
之后把你的`test.tex`放到`ptex-ng-dist`文件夹下，并切换到此文件夹下。
然后执行`./bin/linux-i386/aptex +aplatex test.tex`看结果。

**Comment by tan9p** [comment]
故障依旧，依然是上面的错误

**Comment by clerkma** [comment]
debian的版本号多少，你编译的ptex-ng的commit的hash是多少。
你想让我帮你解决问题，就构造出让我复现的例子。
要么截图，要么给一个vbox镜像，各种手段都可以。
总之，你想解决问题，不要老是强调在你机器上有错误，你得让我这也能复现你的问题。

我装debian 10和debian 9都是在虚拟机中装的，都是i386，改了之后都没问题了。
我大概花了两个半天处理这个事。
你倒好，光说你那有问题有问题。我不掌握你的机器，不能复现！！！
你听不听的明白？？？！！！

**Comment by tan9p** [comment]
抱歉，因为编译的时候没有clean，导致故障依旧。
今天在所有的"Invalid argument"后面都做了记号，清理后在编译，问题解决了。
谢谢！添麻烦了

**Comment by clerkma** [comment]
有别的问题的时候再另外提吧。

**Comment by ShikiSuen** [comment]
@clerkma 你设定一个 issue 提报范本，这样的话大家在提报问题时就知道你在期待哪些具体的资讯条目。

**Comment by ShikiSuen** [comment]
@clerkma 
https://help.github.com/en/articles/creating-issue-templates-for-your-repository

**Comment by clerkma** [comment]
我已经放弃了。因为很多问题他们说的信息再“清楚”也不行。“清楚”不意味着有效。
一个命令行软件，对于大部分人来说，他们可能敲命令都会出问题。
而在这种情况下，更别说cmd环境被破坏造成了其他的问题了。
所以，很多时候，一个问题就变成一组问题。

就这个issue来说，我已经没办法想象为什么会出现想重新编译代码却不做清理的问题。
当然，这个有我的问题，我没在README里面说代码清理需要跑`clean-aptex.sh`。
但是，我中间说的`ptex-ng-dist`，“拖最新的代码编译ptex-ng”，这话似乎就是没有被理解。

我能怎么办？什么办法都没有。知乎上这样给我私信发问题说跑不起来的少说还有四五个。
我也在反思：我为什么要牺牲我的休息时间去解决这些个不清不楚的问题？！
我不知道写个手册能不能解决这一类的问题。从我的经验上看，文档写了依然会有人提这类问题。
