### ISSUE TITLE
Bad installation through http://www.tug.org/~preining/tlptexlive/

### ISSUE THREAD

**Issue by ncihnegn** [clerkma/ptex-ng#4]
ptex-ng .\test-plain.tex
This is pTeX-ng, Version 3.14159265 (W32TeX) (preloaded format=ptex-ng)
entering extended mode
(test-plain.tex [1
ptex-ng :warning: Could not locate a virtual/physical font for TFM "uprml-h".
ptex-ng :warning: >> There are no valid font mapping entry for this font.
ptex-ng :warning: >> Font file name "uprml-h" was assumed but failed to locate that font.
ptex-ng :fatal: Cannot proceed without .vf or "physical" font for PDF output...

But uptex works fine.

**Comment by clerkma** [comment]
请给出`test-plain.tex`文件内容以及命令`kpsewhich uprml-h.vf`的输出内容。

**Comment by ncihnegn** [comment]
I figured it out. It needs the jfontmaps package.

**Comment by lhttjdr** [comment]
In my case, I add the \special command to the beginning of my .tex file in order to specify a self-created map-file. It works for me.
In addition, although the jfontmaps package is installed, it does not work. Maybe it need some extra settings.
