### ISSUE TITLE
增加一些原语

### ISSUE THREAD

**Issue by stone-zeng** [clerkma/ptex-ng#40]
LaTeX3 有一些新增功能需要额外的原语支持，而其他引擎（pdfTeX、XeTeX、LuaTeX、upTeX）基本都已经实现：

- 展开控制：
  - `\expanded`
- 时间：
  - `\(pdf)elapsedtime`
  - `\(pdf)resettimer`
- 文件信息：
  - `\(pdf)filedump`
  - `\(pdf)mdfivesum`
  - `\(pdf)filesize`
  - `\(pdf)filemoddate`
- 随机数：
  - `\(pdf)normaldeviate`
  - `\(pdf)randomseed`
  - `\(pdf)setrandomseed`
  - `\(pdf)uniformdeviate`

**Comment by clerkma** [comment]
我本身对LaTeX3的这些primitive的需求比较消极。
因为有些东西确实不该是底层primitive要做的。
但是，这并不影响我把这些primitive加进去。
问题不大，下周估计就加进去了。

**Comment by clerkma** [comment]
预计周末上这些新primitive。除了这些，还加了：

- `\pdflastxpos`
- `\pdflastypos`
- `\pdfsavepos`

**Comment by clerkma** [comment]
添加完了。
