### ISSUE TITLE
Windows10生成PDF排版混乱

### ISSUE THREAD

**Issue by woxj** [clerkma/ptex-ng#41]
Windows10 TexLive2019 ptex-ng
![image](https://user-images.githubusercontent.com/53204626/62636458-2c28f900-b96c-11e9-8ce3-247e64012dd0.png)

参考了[issue ](https://github.com/clerkma/ptex-ng/issues/33)
可以正常编译[文件1](https://github.com/clerkma/ptex-ng-dist/blob/master/test/test-otf-aozora-tate.tex)
编译文件[文件2](https://github.com/clerkma/ptex-ng-dist/blob/master/test/test-otf-latex.tex)
打印log如下，[完整文件](https://github.com/woxj/FigureBed/blob/master/test-otf-latex.log)

> 
```
This is Asiatic pTeX, Version 3.14159265 (W32TeX) (preloaded format=ptex-ng 2019.8.7)  7 AUG 2019 23:26
entering extended mode
**test-otf-latex.tex
(test-otf-latex.tex
! Undefined control sequence.
l.2 \documentclass
                  [12pt]{article}
? 
! Undefined control sequence.
l.3 \DeclareFontFamily
                      {JY2}{fandolsong}{}
? 
! Undefined control sequence.
l.4 \DeclareFontShape
                     {JY2}{fandolsong}{m}{n}{<->s*[0.962216]ot:FandolSong-Re...
```
已安装fandol字体
编译以下文件
```
\documentclass{ujarticle}
\begin{document}
comprehension more韩愈
\end{document}
```
log如下
```
This is Asiatic pTeX, Version 3.14159265 (W32TeX) (preloaded format=ptex-ng 2019.8.7)  7 AUG 2019 23:44
entering extended mode
**d.tex
(d.tex
! Undefined control sequence.
l.1 \documentclass
                  {ujarticle}
? 
! Undefined control sequence.
l.2 \begin
          {document}
? 
[1] )
Output written on d.dvi (1 page, 312 bytes).
Output written on d.pdf (1 page, 5936 bytes).

```
改成`\documentclass{article}`也还是报` Undefined control sequence`
又用了[嵌入版](https://zhuanlan.zhihu.com/p/27051223)可以正常编译，请问有哪些需要补充的操作步骤吗？

**Comment by stone-zeng** [comment]
LaTeX 文件你得用 `platex-ng` 或者 `aplatex` 编译而不是 `ptex-ng`/`aptex`……
