### ISSUE TITLE
计时、随机数有关原语无效 

### ISSUE THREAD

**Issue by stone-zeng** [clerkma/ptex-ng#43]
测试文件 `test.tex`：

```tex
\documentclass{minimal}
\ifdefined\XeTeXversion
  \let\pdfelapsedtime    \elapsedtime
  \let\pdfresettimer     \resettimer
  \let\pdfsetrandomseed  \setrandomseed
  \let\pdfrandomseed     \randomseed
  \let\pdfnormaldeviate  \normaldeviate
  \let\pdfuniformdeviate \uniformdeviate
\fi
\begin{document}
\begin{tabular}{l@{\quad}l}
  \verb|\the\pdfelapsedtime|     & \the\pdfelapsedtime     \\
  \verb|\pdfresettimer|          & \pdfresettimer          \\
  \verb|\the\pdfelapsedtime|     & \the\pdfelapsedtime     \\
  \verb|\pdfsetrandomseed 0|     & \pdfsetrandomseed 0     \\
  \verb|\the\pdfrandomseed|      & \the\pdfrandomseed      \\
  \verb|\pdfnormaldeviate|       & \pdfnormaldeviate       \\
  \verb|\pdfuniformdeviate 1000| & \pdfuniformdeviate 1000 \\
\end{tabular}
\end{document}
```

使用下述命令编译：

```sh
pdflatex test
xelatex test
uplatex test && dvipdfmx test.dvi
platex-ng test
```

pdfTeX 运行结果：

![image](https://user-images.githubusercontent.com/18233088/63918290-feb50400-ca6e-11e9-8194-1909180c5639.png)

XeTeX 运行结果：

![image](https://user-images.githubusercontent.com/18233088/63918336-155b5b00-ca6f-11e9-94cf-688bc3308c4b.png)

upTeX 运行结果：

![image](https://user-images.githubusercontent.com/18233088/63918420-4045af00-ca6f-11e9-8202-bd40f987668a.png)

pTeX-ng 运行结果：

![image](https://user-images.githubusercontent.com/18233088/63918460-53587f00-ca6f-11e9-96f6-41d988b3fdae.png)

**Comment by clerkma** [comment]
已修复，见[3916136](https://github.com/clerkma/ptex-ng/commit/391613648319bc7367d30d23a20313b24fb7a610)。
