### ISSUE TITLE
\pdfcreationdate no-op?

### ISSUE THREAD

**Issue by aminophen** [clerkma/ptex-ng#44]
Commit message 3b3ad2b says it added \pdfcreationdate, but it returns nothing.

``` tex
\message{\pdfcreationdate}\bye
```

**Comment by clerkma** [comment]
fixed in [bd2aa05](https://github.com/clerkma/ptex-ng/commit/bd2aa055d44e5e11812cc6f77ef660b34f148cf2).

**Comment by aminophen** [comment]
Confirmed, thanks!
