### ISSUE TITLE
随机数没有正确初始化

### ISSUE THREAD

**Issue by stone-zeng** [clerkma/ptex-ng#46]
```tex
% plain tex
\pdfuniformdeviate100  % 或者 \uniformdeviate
\bye
```

编译后得到 0，而其他引擎则给出非零值。设置种子后（e.g. `\pdfsetrandomseed20`），编译结果正常。

**Comment by clerkma** [comment]
fixed in [877fbf9cb99468a8ccb34a6358dcda53f2a0b889](https://github.com/clerkma/ptex-ng/commit/877fbf9cb99468a8ccb34a6358dcda53f2a0b889).
