### ISSUE TITLE
现行的安装方法404了（tltexjpの変化の原因で、今までの方法では、ptex-ngをインストールすることが出来なくなったようです）

### ISSUE THREAD

**Issue by xisang233** [clerkma/ptex-ng#49]
（贴别的issue似乎在那边也会有显示，为了防止对方看不懂，加上了一段蹩脚的日语解释）

`tlmgr repository add http://texlive.texjp.org/current/tltexjp tltexjp`
主要问题似乎出在这一行，点开http://texlive.texjp.org/current/tltexjp 网页后发现404了。
于是我浏览tltexjp项目的issue，发现似乎是因为这个repository在texlive2021中会产生一个奇怪的bug，所以小组决定把这个文件夹删掉了，但是旧年份中的相应目录并没有被删除（详见https://github.com/texjporg/tltexjp/issues/5 ）。
于是我作死改成

 `tlmgr repository add http://texlive.texjp.org/2020/tltexjp tltexjp`

发现安装成功了，但是遇到了和楼上相同的.fmt的问题。

以及我的使用环境也有一丢丢怪异，是在overleaf提供的社区版本docker里面（Texlive版本是2021）。有空的话我会在物理机上再测试下。

**Comment by clerkma** [comment]
预计五月中旬解决，我太忙了，暂时抽不出来时间
