### ISSUE TITLE
一个bug和一个建议

### ISSUE THREAD

**Issue by Wongboo** [clerkma/ptex-ng#50]
1.这是我运行的命令行结果部分显示
```
This is Asiatic pTeX, Version 3.141592653 (preloaded format=platex-ng)
entering extended mode
(c:/Users/90834/Desktop/PDE/PDE2/report
```
实际上我的文件名为report.tex，我的vscode的问题解析都无法指引至原tex文件，因为他总是尝试解析```c:\Users\90834\Desktop\PDE\PDE2\report```，实际上应该加上后缀.tex，推测命令行输出添加.tex可以使此项功能正常
2.为什么不考虑默认执行
```
\def\pgfsysdriver{pgfsys-dvipdfm.def}
```

**Comment by stone-zeng** [comment]
1. 带或者不带 `.tex` 扩展名 TeX 引擎可以都接受，这里更多是 VS Code 的问题
2. `ptex-ng` 也可以配合其他 driver 使用，未必得是 `dvipdfm`

**Comment by Wongboo** [comment]
@stone-zeng 烦您说一下```ptex-ng```怎么配合其他driver，我这边没看到此类命令行参数

**Comment by Wongboo** [comment]
我懂了，找到问题了，```ptex-ng```在Windows不会自动将路径分隔符`\`,替换为`/`，因此`.\report.tex`将会失败，此外由于latexmk内部默认行为会将`/`替换为`\`，于是，`ptex-ng`不加`-cd-`将会编译失败，但加入`-cd-`也只是治标不治本，因为synctex依旧会失效，正确的做法是让`latexmk`加入`-MSWinBackSlash-`，或者让`ptex-ng`中检测到Windows环境后自动将路径分隔符`\`,替换为`/`，建议完成这一Windows上的修正

**Comment by Wongboo** [comment]
至于为何有的时候会丢失`.tex`扩展名，我也不清楚

**Comment by stone-zeng** [comment]
> 烦您说一下`ptex-ng`怎么配合其他driver，我这边没看到此类命令行参数

就用别的驱动（`dvips`、`dvisvgm` 之类）去编译生成的 dvi 文件啊

> 我懂了，找到问题了，`ptex-ng`在Windows不会自动将路径分隔符`\`,替换为`/`，因此`.\report.tex`将会失败，此外由于latexmk内部默认行为会将`/`替换为`\`，于是，`ptex-ng`不加`-cd-`将会编译失败，但加入`-cd-`也只是治标不治本，因为synctex依旧会失效，正确的做法是让`latexmk`加入`-MSWinBackSlash-`，或者让`ptex-ng`中检测到Windows环境后自动将路径分隔符`\`,替换为`/`，建议完成这一Windows上的修正

你是不是应该区分一下 `latexmk` 的选项和 `ptex-ng` 的选项……

**Comment by Wongboo** [comment]
@clerkma, 我拿`lualatex/pdflatex/xelatex`测试了一下，像`.\a.tex`的路径也不支持，但（在Windows下）像`C:\happy\a.tex`的路径是支持的

**Comment by Wongboo** [comment]
@clerkma ，意思是xelatex在1，2是类似并行的吧，而且还有一个问题，就是`latexmk`时，`xelatex`前几次会用`no-pdf`这样就节约了几次2的调用，但现在有`bib`用`latexmk`的话，其四种模式：`latex`，`xelatex`， `pdflatex`， `lualatex`
- `xelatex`， `lualatex`配合不了
- `latex`会显示`dvi`和`pdf`有差异，不让我继续
- `pdflatex`得用
```
        "-e",
        "$pdflatex = 'platex-ng --shell-escape';$bibtex = 'pbibtex'; $dvipdf = 'dvipdfmx %O -o %D %S'; $do_cd = 1; $recorder = 0",
        "-output-format=pdf",
        "%DOC%"
```
会造成多次2的调用浪费时间，于是此例中若想解决bib的编译，我这边的时间对比将更加悬殊

**Comment by Firestar-Reimu** [comment]
windows上`./1.tex`和`1.tex`不一样的问题在xelatex、lualatex等上都有发生，应该是powershell的问题
