### ISSUE TITLE
请问m1 mac版的怎么安装

### ISSUE THREAD

**Issue by fierceX** [clerkma/ptex-ng#52]
看了历史的issues，Mac版的链接基本都挂了。包括阿里云的。

能不能发个mac版的链接，编译太麻烦了。另外，我用tltexjp安装，提示不支持的cpu类型

**Comment by clerkma** [comment]
那我得给你写个脚本，稍等一两天。

**Comment by fierceX** [comment]
@clerkma 谢谢

**Comment by clerkma** [comment]
m1版的mac还是很麻烦。项目里面的那个README里面的repo的mac版binary，按道理说也能安装。
只不过m1的macOS会检查二进制的内容，如果不签名是不能运行的，会给出安全警告。
不过，在弹出安全警告之后，手动允许运行倒是也可以解决不能运行的问题，但是对用户还是很麻烦。
我签名之后再试吧。

**Comment by fierceX** [comment]
@clerkma https://www.hemibit.com/2021 你说的是这个地址吗，我直接打开是403

**Comment by clerkma** [comment]
这个地址不能直接访问。你试过README里面的再看看。
