### ISSUE TITLE
在texlive2023 for windows中添加ptex-ng时出现错误了

### ISSUE THREAD

**Issue by djunhao** [clerkma/ptex-ng#55]
目前我已经安装了最新的texlive2023 for windows。我一直很希望能用上ptex-ng，于是，我按照本仓库的README准备添加ptex-ng到我的texlive2023中。
``tlmgr update --self --all ``
``tlmgr repository add https://www.hemibit.com/2021 ptexngdist ``
``tlmgr pinning add ptexngdist "*" ``

这三步都很顺利。但是当我执行
``tlmgr install ptex-ng ``

时出现错误提示了：

> tlmgr.pl: fmtutil-sys --byengine ptex-ng --no-error-if-no-format --no-error-if-no-engine=luametatex,luajithbtex,luajittex,mfluajit --status-file=C:\Users\NORTHS~1\AppData\Local\Temp\7kxFMA8gEG\PlpESePbOz failed (status 2), output:
fmtutil: fmtutil is using the following fmtutil.cnf files (in precedence order):
fmtutil:   c:/portable/texlive/2023/texmf-dist/web2c/fmtutil.cnf
fmtutil: fmtutil is using the following fmtutil.cnf file for writing changes:
fmtutil:   c:/portable/texlive/2023/texmf-config/web2c/fmtutil.cnf
fmtutil [INFO]: writing formats under c:/portable/texlive/2023/texmf-var/web2c
fmtutil [INFO]: --- remaking ptex-ng with ptex-ng
fmtutil [INFO]: --- remaking platex-ng with ptex-ng
fmtutil [ERROR]: not building ptex-ng due to missing engine: ptex-ng
fmtutil [ERROR]: not building platex-ng due to missing engine: ptex-ng
fmtutil [INFO]: not selected formats: 24
fmtutil [INFO]: failed to build: 2 (ptex-ng/ptex-ng ptex-ng/platex-ng)
fmtutil [INFO]: total formats: 26
fmtutil [INFO]: exiting with status 2
C:\portable\texlive\2023\bin\windows\runscript.tlu:921: command failed with exit code 2:
perl.exe c:\portable\texlive\2023\texmf-dist\scripts\texlive\fmtutil.pl  --sys --byengine ptex-ng --no-error-if-no-format --no-error-if-no-engine=luametatex,luajithbtex,luajittex,mfluajit --status-file=C:\Users\NORTHS~1\AppData\Local\Temp\7kxFMA8gEG\PlpESePbOz
  ERROR: ptex-ng.fmt/ptex-ng platex-ng.fmt/ptex-ng
tlmgr.pl: package log updated: C:/portable/texlive/2023/texmf-var/web2c/tlmgr.log
tlmgr.pl: command log updated: C:/portable/texlive/2023/texmf-var/web2c/tlmgr-commands.log
tlmgr.pl: An error has occurred. See above messages. Exiting.

是ptex-ng 与新版的texlive不兼容吗？

**Comment by clerkma** [comment]
那个repo里面的宏还是能用的，但是binary不可用。
手动编译之后，把ptex-ng复制到texlive里面去就能用了。
platex-ng命令，你可以把exe复制之后改名，或者用mklink做一下链接。
等opentype代码做了大规模更新之后，我会更新源的。
