### ISSUE TITLE
冒昧求教，如何在MiKTeX 中使用 ptex-ng？

### ISSUE THREAD

**Issue by YanMing-lxb** [clerkma/ptex-ng#56]
想在 MiKTeX 中使用 ptex-ng 但是不会编译这个系统，请问如何才能在 MiKTeX 使用？
感谢大佬！！！

**Comment by clerkma** [comment]
我已经很多年没用过MikTeX了。
目前pTeX-ng的代码是基于TeX Live的，修改了之后大概能在MikTeX里面使用。
不过我也没测试过。最近代码会频繁更新，等OpenType支持做的更好了之后再来试试吧。
