### ISSUE TITLE
usage 中 README 的 "Compile Your Document" 示例疑似不对 ?

### ISSUE THREAD

**Issue by zongpingding** [clerkma/ptex-ng#58]
仓库中的如下位置:

https://github.com/clerkma/ptex-ng/blob/93c50bc6570823c7c52168a165bd278cee162c49/usage/README.md?plain=1#L19-L31

的示例是否有误 ? 我按照默认方式生成 `.fmt` 文件，生成的3个 format 文件为:
* ptex-ng.fmt
* platex-ng.fmt
* platex-dev-ng.fmt

所以上述的内容是否应该更改为如下呢?

>  ``` 
>  ptex-ng +platex-ng doc.tex 
>  ``` 
>  or 
>  ``` 
>  ptex-ng +platex-dev-ng doc.tex 
>  ``` 
>  or 
>  ``` 
>  ptex-ng -format=platex-ng doc.tex 
>  ```

**Comment by clerkma** [comment]
是错了。但实际该用aptex/aplatex的，ng的后缀也该要去掉了。

**Comment by zongpingding** [comment]
> 是错了。但实际该用aptex/aplatex的，ng的后缀也该要去掉了。

其实也不算啥问题，但是对第一次编译安装的用户来说也算是一个小坑了。
