### ISSUE TITLE
\inhibitglue 失效？

### ISSUE THREAD

**Issue by leo-liu** [clerkma/ptex-ng#6]
测试代码：

```latex
% !TeX program  = APLaTeX
% !TeX encoding = UTF-8
\documentclass{article}
\DeclareKanjiFamily{JY2}{song}{}
\DeclareFontShape{JY2}{song}{m}{n}{<-> upschrm-h}{}
\special{pdf:mapline upstsl-h UniGB-UTF16-H simsun.ttc}
\def\kanjifamilydefault{song}
\begin{document}

文字abc

文字\inhibitglue abc

文字\footnote{脚注}文字

文字\inhibitglue\footnote{脚注}\inhibitglue 文字

\end{document}
```

![1](https://cloud.githubusercontent.com/assets/570611/13913350/d57a9c2a-ef80-11e5-9b42-f8dbf8b89561.png)

而且不只是 `ptex-ng` 的问题，我用 `uplatex` 编译，`\inhibitglue` 也无效。所以可能是上游的问题？

@clerkma

**Comment by qinglee** [comment]
`\inhibitglue` 抑制的是 JFM 中设置的 glue，比如标点符号前/后的 glue：

    文字\inhibitglue （文字）\inhibitglue 文字

    文字（文字）文字

这种中西文之间的 glue 好像得用 `\noautoxspacing` 来抑制。

**Comment by leo-liu** [comment]
呃，抱歉，是我理解有问题。`\inhibitglue` 主要是缩减前面标点产生的 glue。

可是 `\noautoxspacing` 是对整段文字而不是单点起作用的啊，这里也不应该用。

我看 `jsarticle.cls` 里面的定义
```
\let\footnotes@ve=\footnote
\def\footnote{\inhibitglue\footnotes@ve}
\let\footnotemarks@ve=\footnotemark
\def\footnotemark{\inhibitglue\footnotemarks@ve}
```
我以为是用来缩和前面汉字间距的。这样说来只是为了缩减与前面标点的间距。
——但与汉字也不应该有间距吧？

我试了一下，要禁止汉字与西文之间加的 xspacing，用 `\null` 不行，不过用 `\rule{0pt}{0pt}` 有效。
我在 [pTeX 页面](http://ascii.asciimw.jp/pb/ptex/base/xkanjiskip.html#xkanjiskip) 没见到相关说明。不知道日文习惯怎么手工调整这个。

**Comment by qinglee** [comment]
最新的 upLaTeX 2016/04/17u00 会处理这个问题，是通过在脚注编号前后加 `\null` 来实现的：https://github.com/texjporg/uplatex/blob/master/uplcore.ltx#L967-969
