### ISSUE TITLE
\magnification 命令无效？

### ISSUE THREAD

**Issue by mtf-tpxs** [clerkma/ptex-ng#9]
请教一个问题：今天在 plain TeX 中使用 pTeX-ng，发现 \magnification 命令无效，无论后面使用诸如 \magstep5 之类还是 5000 这样的数字，都无效，仍然是原来的大小。而相同的内容使用 pdfTeX、XeTeX、LuaTeX、pTeX、upTeX 编译，都可以正常放大。

最小示例：

\magnification=\magstep5

ABCDXYZabcdxyz

$ABCDXYZabcdxyz$

0123456789

$0123456789$

\bye

我已经用 2016.4.24 更新的 W32TeX 中的 pTeX-ng 试验过了（不过是安装到了 TeX Live 2015 里边，确认安装后刷新过），还是无效。请问是哪里出了问题？谢谢！

**Comment by clerkma** [comment]
已经修正，等待更新即可。但是，DVIPDFMX和PDFTeX的行为不太一致。

**Comment by mtf-tpxs** [comment]
非常感谢您的回复！

**Comment by clerkma** [comment]
@Man-Ting-Fang 啊，这个bug今天才修，因为有个类似的issue。
最近加了MSVC的编译脚本，你可以试试自己编译更新看一看。
（安装VS 2015/2017或者[Visual C++ 2015 Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)编译皆可）
